# Numpy

Numpy es la abreviación de Numerical Python. Está diseñado para mejorar la eficiencia de los arrays.

Cuando llamamos a un número, por ejemplo el número 5, el ordenador lee en binario: 00000101 el cual ocupa 8 bytes (int64). Sin embargo, cuando utilizamos Numpy el ordenador lo lee de tal forma (int32) que ocupa 4 bytes. Podemos especificar que lo lea de otra forma si no necesitamos el int32. Por ejemplo int16 (16bits o 2 bytes), int8 (8bits o 1 byte).

#### ELEMENT-WISE operation:
allows you to distribute the operation over the elements of a data container

##  Índice

0. Load Numpy


1. Numpy ndarray

    1.1 Array unidimensional

    1.2 Array multidimensional

    1.3 Datatypes for ndarrays

    1.4 Arithmetics with numpy arrays

    1.5 Basic Indexing and Slicing

        1.5.1 Unidimensional Array

        1.5.2 Bidimensional Array

        1.5.3 Multidimensional Array

    1.6 Reorganizicing Arrays

    1.7 Universal Functions: Fast Element-Wise Array Functions

    1.8 Binary ufuncs

    1.9 Array-Oriented Programming with Arrays

        1.9.1 Mathematical and Statistical Methods

        1.9.2 Sorting

        1.9.3 Unique and Other Set Logic


2. Pseudorandom Number Generation

##  Load Numpy (remember to pip install numpy first)

In [1]:
import numpy as np

## 1. NumPy ndarray (A multidimensional array object)

Una de las características de Numpy es la capacidad de crear un objeto array de N-dimensiones o un ndarray.

## 1.1 Array unidimensional

In [2]:
# Generamos un array aleatorio

data = np.random.randn(2,3)
data

array([[ 0.17411927,  0.67581712,  1.43489092],
       [-0.24612821,  0.87120463,  0.95308664]])

In [3]:
# Generamos un array 

data_2 = np.array([1,2,3])
data_2

array([1, 2, 3])

In [4]:
# Generamos un array a apartir de una lista

data3 = [6,7.5,8,9.5]

data_3 = np.array(data3)
data_3

array([6. , 7.5, 8. , 9.5])

#### shape y dtype

shape: tupla que nos indica el tamaño de la dimensión del array

dtype: un objeto que nos describe el data type del array. A no ser que se especifique, np.array intenta dar un buen data type al array creado

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

In [7]:
data_2.dtype

dtype('int32')

## 1.2 Array multidimensional

In [8]:
# Creamos un array bidimensional

data = [[1,2,3,4], [5,6,7,8]]

arr2 = np.array(data)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### shape y ndim
ndim: nos indica la dimensión del array


In [9]:
arr2.shape

(2, 4)

In [10]:
arr2.ndim

2

In [11]:
arr2.dtype

dtype('int32')

#### zeros, ones, empty
zeros: crea un array de sólo 0

ones: crea un array de sólo 1

empty: crea arrays vacíos (no es del todo seguro)

In [12]:
# Creamos un array unidimensional de 10 columnas x 1 fila

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# Creamos un array multidimensional de 3 filas x 6 columnas

np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
# Creamos un array de 2 matrices, 3 filas x 2 columnas

np.empty((2,3,2))

array([[[1.07630968e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.20075551e-075]],

       [[5.06173320e-038, 2.44136298e-052],
        [3.92875546e-033, 2.01911580e-076],
        [5.94313496e-038, 7.96386487e-042]]])

#### full
full: rellena todas las casillas del valor asignado

In [119]:
np.full((2,3), 99, dtype = "float32")

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

#### arange 
arange: es el range de python pero en numpy

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### identity y eye 
Ambas sirven para crear una matriz diagonal NxN 

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Existen más Array creation functions

## 1.3 Data types for ndarrays
El dtype es un objeto especial que contiene la información que el ndarray necesita interpretar

In [18]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://i.gyazo.com/ec008ad70e6250ac34703a35ed9a4d83.png", width = 600)

#### astype
astype: método que nos permite convertir un array desde un dtype a otro

In [19]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [20]:
float_arr = arr.astype("float")
float_arr.dtype

dtype('float64')

In [21]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [22]:
float_arr

array([1., 2., 3., 4.])

#### float to int

A los integer se les añade un floating point. Si queremos cambiar un número float a int, la parte decimal va a quedar truncada:

In [23]:
arr = np.array([3.7,-1.2,0.5,12.9])
arr

array([ 3.7, -1.2,  0.5, 12.9])

In [24]:
arr.dtype

dtype('float64')

In [25]:
arr = arr.astype(np.int32)
arr

array([ 3, -1,  0, 12])

#### string to numeric

Si tenemos un array de strings representando numeros, podemos utilizar astype para convertirlos en forma numérica

In [26]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype = np.string_)

In [27]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [28]:
n = numeric_strings.astype(float)
n

array([ 1.25, -9.6 , 42.  ])

In [29]:
n.dtype

dtype('float64')

## 1.4 Arithmetic with NumPy arrays

#### Operaciones aritméticas

Cualquier operación aritmética entre arrays del mismo tamaño aplica la operación element-wise

In [30]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [32]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

#### Escalares

Las operaciones aritméticas con escalares propagan el argumento escalar a cada elemento en el array

In [33]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [34]:
arr*0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

#### Comparaciones

Podemos hacer comparaciones entre arrays que tengan el mismo tamaño

In [35]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [36]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [37]:
# Comparaciones entre arrays

arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [38]:
# Comparaciones entre array y un valor

bool_array = arr2>2

bool_array

array([[False,  True, False],
       [ True, False,  True]])

## 1.5 Basic Indexing and Slicing
Indexing: selección de elementos por índice

Slicing: porción seleccionada del array 

index X filas X columnas

### 1.5.1 Unidimensional Array

#### Indexing (selección por index)

In [39]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# Un elemento

arr[2]

2

In [41]:
# Una franja de elementos

arr[5:8]

array([5, 6, 7])

In [42]:
# Elementos a la derecha (coge el primero)
arr[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# Elementos a la izquierda (no coge el último)
arr[:5]

array([0, 1, 2, 3, 4])

In [44]:
# Último elemento
arr[-1]

9

#### Broadcasting
Sustitución de un elemento/ franja de elementos

In [45]:
# Sustitución de una franja de elementos

arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

#### Slicing
Fragmentos de una parte seleccionada del array. Estos datos no son copiados y cualquier modificación se reflejará en el array 

In [46]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [47]:
# Cambiamos el valor de un elemento en concreto

arr_slice[1] = 333
arr

array([  0,   1,   2,   3,   4,  12, 333,  12,   8,   9])

In [48]:
# Cambiamos el valor de todos los elementos

arr_slice[:] = 666
arr

array([  0,   1,   2,   3,   4, 666, 666, 666,   8,   9])

In [49]:
# Si queremos que NO tenga efecto sobre el array, necesitamos explicitar una copia

arr_copy = arr.copy()

arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [50]:
arr

array([  0,   1,   2,   3,   4, 666, 666, 666,   8,   9])

In [51]:
Image(url= "https://i.gyazo.com/25ddc133f11562095bbe0d093b5a7b5c.png", width = 600)

### 1.5.2 Bidimensional Array

Considera los elementos de cada índice como un array unidimensional

(indexes, filas X columnas) --> si omitimos el índice, el índice será automáticamente más pequeño que el tamaño de la dimensión del ndarray

In [52]:
# Creamos un array bidimensional (2 filas, 2 columnas) y al no especificar, index 1

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Indexing

In [53]:
# Seleccionar un elemento dentro del array bidimensional

arr2d[2]

array([7, 8, 9])

In [54]:
# Seleccionar un valor dentro del elemento

arr2d[0][2]

3

In [55]:
arr2d[0,2]

3

#### Slicing

In [56]:
arr2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

#### Multiple slicing
Podemos pasar multiples slices e indexes

In [58]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [59]:
arr2d[1,:2]

array([4, 5])

In [60]:
# Seleccionamos una fila en concreto y todas las columnas

arr2d[0, :]

array([1, 2, 3])

In [61]:
# Seleccionamos una columna en concreto y todas las filas

arr2d[:, 2]

array([3, 6, 9])

#### Broadcasting

In [62]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [63]:
Image(url= "https://i.gyazo.com/b545aa99c1e26265fe5be03c4076da5e.png", width = 600)

#### 1.5.3 Multidimensional Array
Especificamos los índices del array

In [64]:
# Creamos un array de 2 índices, 2 filas X 3 columnas (2x2x3)

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Indexing

In [65]:
# Seleccionamos un index del array

arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
# Seleccionamos un elemento dentro del índex

arr3d[0][1]

array([4, 5, 6])

In [67]:
arr3d[0,1]

array([4, 5, 6])

In [68]:
# Seleccionamos un valor dentro del elemento

arr3d[0][1][2]

6

In [69]:
arr3d[0,1,2]

6

In [70]:
arr3d[1,:,0]

array([ 7, 10])

In [71]:
arr3d[:,1,0]

array([ 4, 10])

In [118]:
arr3d[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

## 1.6 Reorganizing Arrays

#### Transponer
Transponer: forma especial del reshaping que devuelve el array al revés sin copiar nada

In [72]:
arr = np.arange(15).reshape((3,5))

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#### Swapping Axes
Swapping Axes: lo mismo que transponer pero para dimensiones más complejas

In [74]:
arr = np.arange(16).reshape(2,2,4)

arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [75]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

#### Reshape

In [124]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

print(" ")
after = before.reshape((4,2))
print(after)

print(" ")
after_2 = before.reshape((2,2,2))
print(after_2)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### vstack: Vertical stacking vectors

In [125]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [126]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

#### hstack: Horizontal stacking vectors

In [128]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [129]:
np.hstack([h1,h2,h1])

array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])

### 1.7 Universal Functions: Fast Element-Wise Array Functions
Una función universal o ufunc es una función que permite aplicar operaciones element-wise en los ndarrays

#### Ejemplos

In [76]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [78]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

#### modf
Devuelve dos funciones, una parte entera y otra decimal de un floating array

In [79]:
arr = np.random.randn(7)*5

arr

array([-3.40035082, -5.67216925, -8.27575871, -1.21324498, -1.72079465,
        2.72778616,  2.45117415])

In [80]:
remainder, whole_part = np.modf(arr)

In [81]:
remainder

array([-0.40035082, -0.67216925, -0.27575871, -0.21324498, -0.72079465,
        0.72778616,  0.45117415])

In [82]:
whole_part

array([-3., -5., -8., -1., -1.,  2.,  2.])

#### in-place 
ufunc acepta un argumento opcional que permite sustituir permanentemente

In [83]:
arr

array([-3.40035082, -5.67216925, -8.27575871, -1.21324498, -1.72079465,
        2.72778616,  2.45117415])

In [84]:
np.exp(arr)

array([3.33615641e-02, 3.44039409e-03, 2.54614809e-04, 2.97231204e-01,
       1.78923910e-01, 1.52989800e+01, 1.16019612e+01])

In [85]:
np.exp(arr,arr)

arr

array([3.33615641e-02, 3.44039409e-03, 2.54614809e-04, 2.97231204e-01,
       1.78923910e-01, 1.52989800e+01, 1.16019612e+01])

In [86]:
Image(url= "https://i.gyazo.com/ebada71084ee975d07033cb306889224.png", width = 600)

### 1.8 Binary ufuncs

Element-wise operaciones que necesitan 2 arrays para funcionar y devuelven un array

#### Example

In [87]:
x = np.random.randn(8)

y = np.random.randn(8)

In [88]:
x

array([ 0.09361619, -0.18109472, -0.91327127, -1.15240484,  1.32951783,
       -0.72998554, -0.07608944,  2.05947623])

In [89]:
y

array([ 0.64670009,  0.37198572, -1.49348726,  0.30894276, -0.00699943,
       -1.26206122,  0.63431352,  0.35738431])

In [90]:
np.maximum(x,y)

array([ 0.64670009,  0.37198572, -0.91327127,  0.30894276,  1.32951783,
       -0.72998554,  0.63431352,  2.05947623])

In [91]:
Image(url= "https://i.gyazo.com/7015e2057867736a577db80893e1718e.png", width = 600)

## 1.9 Array-Oriented Programming with Arrays

NumPy nos permite simplificar muchas tareas con expresiones array, que de otra forma tendrían que ser llevadas acabo mediante loops. Esto se denomina vectorización

Vectorización: reemplazar loops con expresiones array. 

### 1.9.1 Mathematical and Statistical Methods
Funciones matemáticas que permiten calcular estadíticas sobre un array entero o sobre los datos que los axis contienen

#### Ejemplos sobre Arrays enteros

In [92]:
arr = np.random.randn(5,4)

arr

array([[ 1.65003502,  0.23399502,  0.39680669,  0.78936503],
       [ 1.81905507,  0.40525507, -0.39071801, -0.37455496],
       [-1.08965572,  0.75488808, -0.56736213,  1.65911619],
       [-1.24460501, -0.37392791,  0.26871222, -0.82873423],
       [-0.32882218, -0.2201465 ,  0.14162352,  0.52099046]])

In [93]:
arr.mean()

0.16106578578483058

In [94]:
np.mean(arr)

0.16106578578483058

In [95]:
arr.sum()

3.2213157156966115

#### Ejemplos sobre axis concretos

In [96]:
# Media de filas (axis = 1) Compute mean across the columns

arr.mean(axis=1)

array([ 0.76755044,  0.36475929,  0.18924661, -0.54463873,  0.02841133])

In [97]:
# Media de un fila en concreto (la primera) 
arr[0, :-1].mean()

0.7602789098281436

In [98]:
# Suma de columnas (axis = 0) Compute sum down the rows

arr.sum(axis=0)

array([ 0.80600717,  0.80006377, -0.15093771,  1.76618248])

In [99]:
# Suma de una columna en concreto

arr.sum(axis=0)[0]

0.8060071721726485

In [100]:
Image(url= "https://i.gyazo.com/cf9c1ea9ff5cf390a30129183c18a92b.png", width = 600)

### 1.9.2 Sorting
NumPy arrays can be sorted in-place with the sort method

In [101]:
arr = np.random.randn(6)

arr

array([ 0.15428663,  0.83718987, -0.49168296, -0.14291223, -0.17957911,
       -2.00159884])

In [102]:
arr.sort()

#### Sorting values in multidimensional arrays
Podemos ordenar secciones unidimensionales de los array multidimensionales según el axis

In [103]:
arr = np.random.randn(5,3)

arr

array([[ 1.52805346,  0.17889621,  0.29375625],
       [ 0.97641842, -2.1119706 ,  1.02203704],
       [ 0.20883147,  0.61717698, -1.33630149],
       [ 0.50074735,  0.62281495,  0.40457343],
       [ 0.36638635, -0.24527345, -2.09947218]])

In [104]:
arr.sort(1)

arr

array([[ 0.17889621,  0.29375625,  1.52805346],
       [-2.1119706 ,  0.97641842,  1.02203704],
       [-1.33630149,  0.20883147,  0.61717698],
       [ 0.40457343,  0.50074735,  0.62281495],
       [-2.09947218, -0.24527345,  0.36638635]])

### 1.9.3 Unique and Other Set Logic

#### unique
Nos permite ordenar valores únicos en el array

In [105]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [106]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [107]:
Image(url= "https://i.gyazo.com/df916e8b6d74ac3158610b34f972444d.png", width = 600)

## 2. Pseudorandom Number Generation
El módulo numpy.random sustituye al módulo Random de Python.

Son pseudorandom porque se generan siempre en base a un algoritmo (no son del todo aleatorios).

#### Ejemplos

In [108]:
np.random.rand(3,2)

array([[0.65741643, 0.57934334],
       [0.74534264, 0.83754226],
       [0.52653907, 0.76139676]])

In [109]:
np.random.rand(3,2)

array([[0.36137558, 0.57037653],
       [0.58447265, 0.0582805 ],
       [0.08176834, 0.14083669]])

In [110]:
np.random.randn(3,2)

array([[ 1.09882429, -0.14787672],
       [-0.16498963,  0.05868209],
       [ 1.81081644, -0.25584472]])

In [111]:
np.random.randint(1,10)

5

In [112]:
np.random.randint(1,10, size = (3,2))

array([[7, 7],
       [5, 5],
       [1, 1]])

#### seed
seed hace que los números aleatorios sean predecibles. Si queremos que todo el rato se nos generen los mismos números aleatorios, usamos seed

In [113]:
np.random.seed(123)

b = np.random.randn(3,2)

b

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [114]:
b

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [115]:
np.random.seed(321)

c = np.random.randn(3,2)

c

array([[ 0.17251947,  1.63548253],
       [ 0.0373364 , -0.88414969],
       [-1.14319226, -0.62136604]])

In [116]:
c

array([[ 0.17251947,  1.63548253],
       [ 0.0373364 , -0.88414969],
       [-1.14319226, -0.62136604]])

In [117]:
Image(url= "https://i.gyazo.com/f17fd9da079432db31446f69171e9998.png", width = 600)